default: &default
  SECRET_KEY_BASE: 6997a7ec54ffd02ecb1875695a6d1a7e33180eed660b0dce4277e51352385616d5329099f2aab712a7e90fe1a5b625029ff5fee88548bac0130ed001735b653e
  STRIPE_PUBLISHABLE_KEY: pk_test_51IqF32DA96m3rKliyy31qFY1XBMebvCrUavPPdJMhQ7PAJGhIP8lKEFjyaTOoDHpGDbInimFsDboeInLjpsRjaCR00bA3UQmE0
  STRIPE_SECRET_KEY: sk_test_51IqF32DA96m3rKliqKu91BNaVnlvu9tRsSTTuUpURYGx6pFpUadVx7cSjAnrTW6LBJfUku5N3gA4tW7Pm0kzxhZp00Pvy7MTJU
  MOMO_DOMAIN_TEST: "https://test-payment.momo.vn/gw_payment/transactionProcessor"
  MOMO_DOMAIN_PRODUCTION: "https://test-payment.momo.vn/gw_payment/transactionProcessor"
  MOMO_REQUEST_TYPE: "captureMoMoWallet"
  MOMO_PARTNER_CODE: MOMO50VA20210531
  MOMO_ACCESS_KEY: BNl0jkJ8SkoZ9mY1
  MOMO_SECRET_KEY: dJ7RP8wGS51q0PlkC5PbrybIBYw9opd5
  MOMO_HOST: okgoda-travel-application
test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
