default: &default
  STRIPE_PUBLISHABLE_KEY: pk_test_51IqF32DA96m3rKliyy31qFY1XBMebvCrUavPPdJMhQ7PAJGhIP8lKEFjyaTOoDHpGDbInimFsDboeInLjpsRjaCR00bA3UQmE0
  STRIPE_SECRET_KEY: sk_test_51IqF32DA96m3rKliqKu91BNaVnlvu9tRsSTTuUpURYGx6pFpUadVx7cSjAnrTW6LBJfUku5N3gA4tW7Pm0kzxhZp00Pvy7MTJU
test:
  <<: *default

development:
  <<: *default
