development:
 secret_key_base: key
 publishable_key: pk_test_51IqF32DA96m3rKliyy31qFY1XBMebvCrUavPPdJMhQ7PAJGhIP8lKEFjyaTOoDHpGDbInimFsDboeInLjpsRjaCR00bA3UQmE0
 secret_key: sk_test_51IqF32DA96m3rKliqKu91BNaVnlvu9tRsSTTuUpURYGx6pFpUadVx7cSjAnrTW6LBJfUku5N3gA4tW7Pm0kzxhZp00Pvy7MTJU

test:
 secret_key_base:key
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 publishable_key: <%= ENV["publishable_key"] %>
 secret_key: <%= ENV["secret_key"] %>
