development:
  secret_key_base: 6997a7ec54ffd02ecb1875695a6d1a7e33180eed660b0dce4277e51352385616d5329099f2aab712a7e90fe1a5b625029ff5fee88548bac0130ed001735b653e
  stripe_secret_key: 'sk_test_51IqF32DA96m3rKliqKu91BNaVnlvu9tRsSTTuUpURYGx6pFpUadVx7cSjAnrTW6LBJfUku5N3gA4tW7Pm0kzxhZp00Pvy7MTJU'
  stripe_publishable_key: 'pk_test_51IqF32DA96m3rKliyy31qFY1XBMebvCrUavPPdJMhQ7PAJGhIP8lKEFjyaTOoDHpGDbInimFsDboeInLjpsRjaCR00bA3UQmE0'

test:
  secret_key_base:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
